services:
  marketplace:
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    image: marketplace
    ports:
      - "5000:5000"
    depends_on:
      - recommendations

  recommendations:
    build:
      context: .
      dockerfile: recommendations/Dockerfile
    image: recommendations
    ports:
      - "50051:50051"
