# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"n\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12/\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x1d.recommendations.BookCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"1\n\x16RecommendationResponse\x12\x17\n\x0frecommendations\x18\x01 \x03(\t*P\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\t\n\x05SCIFI\x10\x01\x12\x0b\n\x07\x46\x41NTASY\x10\x02\x12\x0e\n\nNONFICTION\x10\x03\x12\x0b\n\x07ROMANCE\x10\x04\x32u\n\x15RecommendationService\x12\\\n\tRecommend\x12&.recommendations.RecommendationRequest\x1a\'.recommendations.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKCATEGORY']._serialized_start=205
  _globals['_BOOKCATEGORY']._serialized_end=285
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=42
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=152
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=154
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=203
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=287
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
